/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thebigscale;


import com.google.common.flogger.FluentLogger;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        logger.atInfo().log(new App().getGreeting());
        SpringApplication.run(App.class, args);
    }
}
